### ISSUE TITLE
Have lat and lon as output in Redcap

### ISSUE THREAD

**Issue by Auricap** [Research-IT-Swiss-TPH/redcap-address-auto-complete#12]
Hi! first of all thank you for developing this wonderful module to obtain "clean" adresses. I use it a lot and I would like to make a map with the addresses I've gathered in Qliksense. For that I need the latitude and longitude of each address instead of x and y. It would be great to have this in next releases, maybe an option in the module configuration to decide wether coordinates or latitude and longitude are provided in the output variable "metadata". Thank you very much for your reply. Best regards.

**Comment by 274188A** [comment]
this has been implemented from the looks of it.

**Comment by tertek** [comment]
@Auricap thank you for using the module.
as @274188A has pointed out, this feature is already available.

To use it, you have to assign a REDCap variable field to "target_meta", within the project-level module configuration:
Target Meta: Select meta field where geo information should be saved. Format is address-id, x, y.

See below a screenshot of how it is used in a project:
![image](https://github.com/Research-IT-Swiss-TPH/redcap-address-auto-complete/assets/75415872/e5925525-c0ed-4ae0-ae23-80c554133fbe)
