### ISSUE TITLE
AAC stuck on loading V14.0.0

### ISSUE THREAD

**Issue by nadha25** [Research-IT-Swiss-TPH/redcap-address-auto-complete#14]
Hi,

We’ve recently upgraded our REDCap version to 14.0.0 and it seems that shortly after the Address Auto Complete has stopped working on our end. We were wondering if this something someone else may have raised ?
EM v3.4.0
REDCap v14.0.0
API https://getaddress.io/

Below is the JS console message.

jQuery.Deferred exception: drop_downaddEventListener is not defined ReferenceError: drop_downaddEventListener is not defined
    at HTMLDocument.<anonymous> (https://itm-dev.redcap.bham.ac.uk/redcap_v14.0.0/DataEntry/index.php?pid=75&id=2&event_id=381&page=address_em:878:2)
    at c (https://itm-dev.redcap.bham.ac.uk/redcap_v14.0.0/Resources/webpack/js/bundle.js?1701361928:2:390551)
    at u (https://itm-dev.redcap.bham.ac.uk/redcap_v14.0.0/Resources/webpack/js/bundle.js?1701361928:2:390853) undefined
D.Deferred.exceptionHook @ bundle.js?1701361928:2
bundle.js?1701361928:2 Uncaught ReferenceError: drop_downaddEventListener is not defined
    at HTMLDocument.<anonymous> (index.php:878:2)
    at c (bundle.js?1701361928:2:390551)
    at u (bundle.js?1701361928:2:390853)
2main.js?1682385680:203 				<div class="red" style="margin:20px 0px;max-width:700px;">
					<b>REDCap crashed due to an unexpected PHP fatal error!</b><br><br>
					<b>Error message:</b> Uncaught Error: Failed opening required &#039;modules\address_auto_complete_v3.4.0\sources./../classes/source.class.php&#039; (include_path=&#039;.;redcap_v14.0.0\Libraries\PEAR\;.;C:\php\pear&#039;) in modules\address_auto_complete_v3.4.0\sources\getaddress_io.source.php:4
Stack trace:
#0 modules\address_auto_complete_v3.4.0\addressAutoComplete.php(558): include_once()
#1 modules\address_auto_complete_v3.4.0\addressAutoComplete.php(503): STPH\addressAutoComplete\addressAutoComplete-&gt;getMappedResultsBySource()
#2 modules\address_auto_complete_v3.4.0\requestHandler.php(15): STPH\addressAutoComplete\addressAutoComplete-&gt;mapResults()
#3 redcap_v14.0.0\ExternalModules\index.php(146): require(&#039;E:\\redcap\\modul...&#039;)
#4 {main}
  thrown<br>
					<b>File:</b> modules\address_auto_complete_v3.4.0\sources\getaddress_io.source.php<br>
					<b>Line:</b> 4<br>
				</div>

**Comment by tertek** [comment]
@nadha25 thank you for reporting this issue.

Can you please update to the latest version of the module and check if the issue persists?

I suppose this has been resolved here: https://github.com/Research-IT-Swiss-TPH/redcap-address-auto-complete/commit/234461485e453b6ec9840d4ef2a18716b785d028

**Comment by tertek** [comment]
Closing since there was no more response. Feel free to reopen in case the issue still remains @nadha25 .
