### ISSUE TITLE
Unknown string in geo location

### ISSUE THREAD

**Issue by govindsoniox** [Research-IT-Swiss-TPH/redcap-address-auto-complete#15]
I searched for the united kingdom address using uk api in built, in the geo code, just before the coordinates, it is saving a unkown string for some reason, in my case I searched John radcliffe hospital ox3 9du , and it adds "YmRkMDk5NGUwZGYzMmM3IDIzNDUxODkxNzggZjAyMzliMjJhZTRkNDhh, 51.7652, -1.22177" in geo code. is it expeted and known?

**Comment by tertek** [comment]
Hi @govindsoniox,
yes it is expected.

That string should be the address-id supplied by API provider. It may be different for every provider, but can be used as a reference for the same provider. 

It is also mentioned in the Module Documentation:
![image](https://github.com/user-attachments/assets/a34cdf81-0f05-4e07-9bba-398280374c01)
